[package]
name = "xrust"
version = "0.4.0"
keywords = ["xml", "json", "xpath", "xslt", "tree"]
categories = ["parser-implementations"]
description = "Support for XPath, and XSLT"
authors = ["Steve Ball <Steve.Ball@explain.com.au>"]
license = "Apache-2.0"
repository = "https://github.com/ballsteve/xrust"
documentation = "https://docs.rs/xrust/"
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decimal = "2.1.0"
lexers = "0.1.2"
nom = "6.2.0"
unicode-segmentation = "1.7.1"
petgraph = "0.6.0"
