[package]
name = "xdm"
version = "0.1.0"
authors = ["Steve Ball <Steve.Ball@explain.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decimal = "2.0.4"
lexers = "0.1.2"
nom = "5.1.2"

